---
- hosts: all
  become: true

  vars:
    webapp_stack_app_containers:
      - { name: www001, public_port: 8001, run_migrations: "yes" }
      - { name: www002, public_port: 8002, run_migrations: "no" }

  pre_tasks:
    - name: Update apt cache if needed.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - role: oefenweb.docker
    - role: webapp_stack
