---
- name: Build Docker images from Dockerfiles.
  community.docker.docker_image:
    build:
      path: "/vagrant/provisioning/{{ item.directory }}"
    name: "{{ item.name }}"
    push: false
    tag: "{{ item.tag }}"
    state: present
    source: build
  with_items: "{{ webapp_stack_docker_images }}"

# Data containers don't need to be running to be utilized.
- name: Run a PgSQL Data container.
  community.docker.docker_container:
    image: data:data
    name: data
    state: present

- name: Run a webapp container.
  community.docker.docker_container:
    image: www:webapp
    name: "{{ item.name }}"
    state: started
    restart_policy: always
    command: python /opt/www/index.py
    ports: "{{ item.public_port }}:3031"
    env:
      POSTGRES_HOST: "{{ ansible_docker0.ipv4.address }}"
      POSTGRES_DB: webapp
      POSTGRES_USER: webapp
      POSTGRES_PASS: na9Chie9Phie6Yeepae1aech
      RUN_MIGRATIONS: "{{ item.run_migrations }}"
  with_items: "{{ webapp_stack_app_containers }}"

- name: Run a PgSQL container.
  community.docker.docker_container:
    image: db:pgsql
    name: db
    state: started
    restart_policy: always
    volumes_from:
      - data
    ports: "5432:5432"
    env:
      POSTGRES_PASSWORD: secretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
