---
- name: Install and configure HAproxy
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Deploy HAproxy error 404 file
  ansible.builtin.template:
    dest: /etc/haproxy/errors/404.http
    src: haproxy/404.http.j2
    owner: root
    group: root
    mode: '0644'

- name: Deploy HAproxy config file
  ansible.builtin.template:
    dest: /etc/haproxy/haproxy.cfg
    src: haproxy/haproxy.cfg.j2
    owner: root
    group: root
    mode: '0644'
    validate: '/usr/sbin/haproxy -c -f %s'
  notify: Restart haproxy

- name: Ensure HAproxy is running
  ansible.builtin.service:
    name: haproxy
    state: started
