---
- name: DROP traffic from outside to PgSQL
  ansible.builtin.package.iptables:
    chain: FORWARD
    action: insert
    in_interface: eth0
    protocol: tcp
    match: tcp
    destination_port: 5432
    jump: DROP
    comment: DROP traffic from outside to PgSQL
  become: true

- name: DROP traffic from outside to webapps running in Docker
  ansible.builtin.package.iptables:
    chain: FORWARD
    action: insert
    in_interface: eth0
    protocol: tcp
    match: tcp
    destination_port: 8000
    jump: DROP
    comment: DROP traffic from outside to webapps running in Docker
  become: true
